# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(936, 708)
        self.btn_seleccionar_carpeta = QtWidgets.QPushButton(Dialog)
        self.btn_seleccionar_carpeta.setGeometry(QtCore.QRect(90, 160, 141, 41))
        self.btn_seleccionar_carpeta.setObjectName("btn_seleccionar_carpeta")
        self.btn_firmar = QtWidgets.QPushButton(Dialog)
        self.btn_firmar.setGeometry(QtCore.QRect(100, 290, 131, 51))
        self.btn_firmar.setObjectName("btn_firmar")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(70, 400, 211, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 120, 431, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 301, 21))
        self.label_2.setObjectName("label_2")
        self.lbl_ubicacion1 = QtWidgets.QLabel(Dialog)
        self.lbl_ubicacion1.setGeometry(QtCore.QRect(30, 210, 241, 41))
        self.lbl_ubicacion1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ubicacion1.setText("")
        self.lbl_ubicacion1.setObjectName("lbl_ubicacion1")
        self.lbl_ubicacion2 = QtWidgets.QLabel(Dialog)
        self.lbl_ubicacion2.setGeometry(QtCore.QRect(30, 350, 251, 41))
        self.lbl_ubicacion2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ubicacion2.setText("")
        self.lbl_ubicacion2.setObjectName("lbl_ubicacion2")
        self.lbl_texto_firma = QtWidgets.QLabel(Dialog)
        self.lbl_texto_firma.setGeometry(QtCore.QRect(10, 0, 121, 21))
        self.lbl_texto_firma.setObjectName("lbl_texto_firma")
        self.edit_nombre = QtWidgets.QLineEdit(Dialog)
        self.edit_nombre.setGeometry(QtCore.QRect(100, 30, 251, 31))
        self.edit_nombre.setObjectName("edit_nombre")
        self.lbl_nombre = QtWidgets.QLabel(Dialog)
        self.lbl_nombre.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_3.setObjectName("label_3")
        self.edit_cargo = QtWidgets.QLineEdit(Dialog)
        self.edit_cargo.setGeometry(QtCore.QRect(100, 70, 251, 31))
        self.edit_cargo.setObjectName("edit_cargo")
        self.mostrar_pdf = QtWidgets.QGraphicsView(Dialog)
        self.mostrar_pdf.setGeometry(QtCore.QRect(370, 10, 551, 681))
        self.mostrar_pdf.setObjectName("mostrar_pdf")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_seleccionar_carpeta.setText(_translate("Dialog", "Seleccionar carpeta"))
        self.btn_firmar.setText(_translate("Dialog", "Firmar PDF\'s"))
        self.label.setText(_translate("Dialog", "Selecciona la carpeta de todos los PDF\'s a firmar"))
        self.label_2.setText(_translate("Dialog", "Selecciona la carpeta donde todos los PDF\'s se van a guardar"))
        self.lbl_texto_firma.setText(_translate("Dialog", "Firma a poner:"))
        self.lbl_nombre.setText(_translate("Dialog", "Nombre:"))
        self.label_3.setText(_translate("Dialog", "Cargo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
